### ISSUE TITLE
kobra head and one question

### ISSUE THREAD

**Issue by djepsylon** [wabbitguy/Kobra_Max#1]
hi, i ve read your post on the kobra firmware, the firmware.bin is the optimal one you have make?
a big thanks for all your great work! really!
another thing, i've maked a hotend cover for the kobra max, can you test it and give me your opinion on this?
https://www.printables.com/fr/model/282490-anycubic-kobra-max-hotend-cover-dual-5010-fan-duct

**Comment by wabbitguy** [comment]
@djepsylon the release I did is all my own work, I have supplied my changes to the other developer because they are releasing the linear advance path, whereas I am not.

I appreciated the offer to test the hotend cover but I don't use 5015 fans, I use are the more quiet 4020 bearing types. Apart from that, I already have redone my own hotend cover with ASA and modified the stock fan outlets for slightly better cooling. Ultimately I don't print many small objects on the Kobra Max so the cooling fans see little to no use.
