### ISSUE TITLE
Just a question to V1.8

### ISSUE THREAD

**Issue by n1k0-83** [wabbitguy/Kobra_Max#11]
Just a quick question: 
When will the statistics be calculated?
Since the first update to your firmware or since the first use of the printer?

Thanks

**Comment by wabbitguy** [comment]
@n1k0-83 I enabled it for the first firmware release I ever did so it's been on since that point. However there was a bug in the way Anycubic was calculating failed prints so while the other items were correct, the total finished print total will be incorrect.

You can reset the totals to zero any time you want as well. M78 S78 will reset all stats to 0.
