### ISSUE TITLE
Surface artifacts in X direction after Switching from Factory Firmware

### ISSUE THREAD

**Issue by servaasusa** [wabbitguy/Kobra_Max#12]
I noticed new surface artifacts (only in the X direction) after switching from factory firmware to this fork. 

![image](https://user-images.githubusercontent.com/32412389/234957764-5cad0044-4dd0-4f16-a83f-a2086658609d.png)

Narrowed it down to X Jerk having changed from 5 to 0 compared to factory defaults. 

Other reports of the issue:
3DPUK on YouTube : https://www.youtube.com/watch?v=nIVVLBzxfNY 

Workaround:
...
step 10 (Sending M502 twice)
step 10.x (Send "M205 X5 Y5")
step 11 : Send M500

Diffing with ANYCUBIC-3D:
https://github.com/ANYCUBIC-3D/Kobra_Max/compare/master...wabbitguy:Kobra_Max:master

line 2519 in source/Marlin/src/module/settings.cpp:
planner.max_jerk.set( 0, DEFAULT_YJERK, DEFAULT_ZJERK); 
vs original:
planner.max_jerk.set(DEFAULT_XJERK, DEFAULT_YJERK, DEFAULT_ZJERK);

The first param being 0, is most likely the cause (probably forcing the default Value to 0 somewhere else):

@wabbitguy can share your build process/script? I found a way to build (not as easy as vanilla marlin) but I would like to mirror your  process so I can keep noise to a minimum when collaborating on this firmware. I should then be able to build,install, and verify this bug/fix on my Max.  Please email servaasusa@gmail.com

**Comment by wabbitguy** [comment]
@servaasusa great catch!! I'd looked everywhere for the reason why it reset to zero, couldn't find the rotten thing. I have no idea how that line managed to duplicate and nop itself out. I went back through my source and at some point, it got changed between releases. According to my logs I haven't even edited anything in the settings.cpp file. I'll mark that down as a mystery.

I've updated the releases now and the source. Thanks for the detective work!

For the build process you need to be a registered KeilARM developer, put some old libraries in the compiler and build it that way. The CPU used on the motherboard precludes any other way to build the firmware because there is no library support for it at this time.

On how Keil is setup, follow these steps:

https://www.reddit.com/r/anycubic/comments/y2waxu/tutorial_how_to_build_anycubic_marlin_source_code/

**Comment by wabbitguy** [comment]
@servaasusa once KeilArm is installed, open the AnyCubic file (it's a PROJECT file so use the Open Project menu item) in the workspace folder. All the files will show on the left side. To compile, smack the F7 key. Or you can compile all the individual files if you make any big changes.

So there's no script or anything like that. And yeah, the complier is a bit brain dead as well. I'll pop you an email.
