### ISSUE TITLE
Other Marlin features

### ISSUE THREAD

**Issue by ghost** [wabbitguy/Kobra_Max#14]
Thanks for your work on this.  Any plans to add other features?  Firmware retraction and input shaping could be of significant benefit to the Kobra Max's monstrous build volume.

I'm trying firmware retraction myself, but I find myself unequal to the task:  I believe I've harvested the relevant source and files from the mainstream Marlin repo, but I'm lost on how to effectively integrate them for a successful build in Keil.  Is there a (relatively) straightforward way to "turn on" features from mainline Marlin so we can test them in this machine?

**Comment by wabbitguy** [comment]
@BlackMulch firmware retraction would be a major work because of the brain dead LCD in use. While implementing it in firmware wouldn't be too difficult, providing the needed controls on the LCD certainly would. Not to mention you'd have to have start GCODEs setup for all the different filaments since there is no "one size retraction" that fits all. Every slicer profile out in the wild would have to change. That'd be very confusing I'd think.

Input shaping is beta at the moment. It requires 2.1.2bugfix branch of Marlin so it's not in a stable release. However, once it is, the chore then becomes to update each and every module in the source code so that the libraries for the specific CPU used on the Tri-Gorilla board can even compile. And once those are updated, about a dozen of them have to be modified to support the LCD for all the current changes implemented (like filament change, pause, stats, etc). Thus it's not just editing a configuration.h file and going forward.

As for using "Mainline" Marlin (from the Marlin Github itself), sadly, no way at all. The CPU (HC32F460) on the motherboard is not supported at this time and no idea when it will be. So it's KeilARM and the Anycubic source or nothing at all. My own version uses some modules from the stable 2.0.8 release that I worked in, not the bug fix branch.

I was interested in input shaping myself but Marlin made the choice to not allow it on delta printers and I prefer to keep all my printers running more or less the same firmware versions. I have several delta's and cartesians so I lost interest in it.

In regards to other features, a couple of us have been looking at things that might be of benefit if they could be shoe horned into the LCD display (the biggest limiting factor).

Mel
