### ISSUE TITLE
No VS compiler?

### ISSUE THREAD

**Issue by zonalimitatore** [wabbitguy/Kobra_Max#18]
This firmware can't be compiled under platformio?

**Comment by maikramer** [comment]
You can wait until i finish my work on having a updated Marlin for the Kobra Max. I'm almost there.
You can build it with platformio and vs code.
https://github.com/maikramer/MarlinKobraMax
I still working on it, but the only things are not working are the runout sensor and the Power Loss recovery.
With my build you can use the updated Linear Advance and the much improved Input Shapping.

**Comment by wabbitguy** [comment]
@zonalimitatore Anycubic didn't use any standard compiler so we were restricted to what we can use. It is either KeilARM compiler or nothing. In order to make it compatible with the more common compilers and even make it more Marlin friendly takes a lot of work to do. More than the printer is worthy of for me.

Mel
