### ISSUE TITLE
Confirm the firmware works

### ISSUE THREAD

**Issue by sxiii** [wabbitguy/Kobra_Max#2]
First of all, I want to thank you @wabbitguy for releasing this. I've tested it yesterday on ABS and it works nicely. I will still have to test the filament change but I'm pretty certain it will go well :) Appreciate your work!

I'd like to know if there's any other developments planned on further improvement of the firmware. Anycubic doesn't seem to be very active at this though. I'd be happy to follow up and test anything that gets implemented asap if needed :)

Lastly, almost completely unrelated question but maybe you could recommend me some fume hood to use with Kobra Max? I was thinking to make a 80% "closed" enclosure for it and connect fume hood somehow (mostly for ABS printing), but I don't see right now how it can easily be done and also for the fume hood, if I should use a factory one, or make my own, or use a "standard" kitchen style one, etc...

P.S. Probably the issues isn't the best "forum" for discussions, feel free to close it at any point :)

Thanks again!

Den

**Comment by wabbitguy** [comment]
@sxiii Thanks for the follow up and for testing! Very helpful. I hadn't really planned on releasing my own fork because of the issues I'd had during my own beta testing phase. Aka I busted some hot end parts trying to get things working correctly. In the end, I finally got it working correctly but with the redefinition of the pause function on the LCD.

In regards to further developments, I can't honestly say at this point. If something in the firmware annoys me beyond a certain point, I'll no doubt crawl back into the code and see if I can fix it. As it stands at the moment there isn't a lot of areas that would benefit from any further "tweaks".  The LCD itself, being closed source, is the single point of all limitations. Modifying the firmware to fix a problem with the LCD seems wrong to me on so many levels, but that's stumbling point with all these cool looking TFT touch displays. They're brain dead.

Anycubic provides enough firmware to print. But they've traditionally left out filament changes with the M600 on almost all of their printers. They want to sell a printer and do as little tech support as possible (as do most of the companies).

re the "fume hood", I print ASA and HIPS. Same toxic fumes. I did print some ABS but found ASA far easier to print so I don't do any ABS any more.

I experimented with a hood as well and found it didn't work well at all. The problem was the main hot end cooling fan and the two print cooling fans. They would blow the fumes out past the area where the hood could catch them. So I experimented with a card board box to use as a temp enclosure, so laid it at the back of the printer and slid it forward as if I was putting the pinter in the box. I didn't go past the Z axis so not a complete enclosure with an open front, just a back partial with an open front. I put one 120mm fan on the top of the box and one at the back of the box. Ran those to a Y adapter for a hose and out a window. Not exactly my best work but it certainly helped a lot. In the end, I moved the printer to a vented room and that works the best.

Mel
