### ISSUE TITLE
Would the FW update work without UI update due to TJC display?

### ISSUE THREAD

**Issue by leonet99** [wabbitguy/Kobra_Max#32]
Hi, I would like to use your firmware on my Kobra Max, but my printer came with TJC display, so the DWIN_SET UI update doesn't work with it (believe me I tried tens of times before I decided to open it up and saw TJC). My printer motherboard is still the old style (Anycubic's original Tri-Gorilla_ProA V1.0.4 using the full size USB-B connector not the micro).
Can I still benefit of using your printer FW update features and refinements but using stock UI, and what would I lose?
Thank you, and all respects for what you guys do for the community!!!

**Comment by wabbitguy** [comment]
@leonet99 that's a really good question. First off, the display would be the usual Anycubic monochrome self. Thus no colour display.

I added in the printer stats page option, so first off that would be gone.

The LCD can also show messages from the Slicer GCODE (M117) so that would be history as well.

But off the top of my head, I think that's about it. Sorry I can't be more exact about it.

Mel
